# Generated by Django 4.2 on 2023-05-11 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scat', models.CharField(max_length=20)),
                ('sdes', models.CharField(max_length=50)),
                ('simage', models.FileField(upload_to='users')),
                ('farmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.registeration')),
            ],
        ),
    ]
