# Generated by Django 4.2 on 2023-05-22 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_product_stock'),
        ('customer', '0010_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='farmid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.registeration'),
        ),
        migrations.AddField(
            model_name='orders',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.product'),
        ),
        migrations.AddField(
            model_name='orders',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='subtotal',
            field=models.IntegerField(null=True),
        ),
    ]
