# Generated by Django 4.2 on 2023-05-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_orders_farmid_orders_pid_orders_qty_orders_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='farmid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='subtotal',
        ),
    ]
