# Generated by Django 4.2 on 2023-05-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_remove_orders_farmid_remove_orders_pid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='password',
        ),
    ]
