# Generated by Django 4.2 on 2023-05-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_orders_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cartid',
        ),
        migrations.AddField(
            model_name='orders',
            name='cartid',
            field=models.ManyToManyField(to='customer.cart'),
        ),
    ]
