# Generated by Django 4.2 on 2023-05-24 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_product_unit'),
        ('customer', '0014_remove_orders_cartid_orders_cartid'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('farmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.registeration')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.product')),
            ],
        ),
    ]
