from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import *
from django.contrib import messages
import string,random
from exfarmer.models import *
from django.core.mail import send_mail
from crop_assessment.settings import EMAIL_HOST_USER

# Create your views here.
def admin_index(request):
    return render(request,"site_admin/admin_index.html") 

def admin_login(request):
    return render(request,"site_admin/admin_login.html") 

def appr_exfarm(request):
    exf=ExpFarmer.objects.all()
    return render(request,"site_admin/appr_exfarm.html",{'exf':exf}) 

def e_approve(request,eid):
    ExpFarmer.objects.filter(id=eid).update(approve=True)
    return redirect('appr_exfarm')

def e_reject(request,eid):
    ExpFarmer.objects.filter(id=eid).update(reject=True)
    return redirect('appr_exfarm')

def send_email(request,id):
   exp=ExpFarmer.objects.get(id=id)
   #sub = forms.Subscribe()
   if request.method == 'POST':
        sub = request.POST['email']
        name= request.POST['name']
        subject = 'Hi, '+format(name) 
        recepient = str(sub)
      
        # get random password pf length 8 with letters, digits, and symbols
        characters = string.ascii_letters + string.digits + string.punctuation
        password = ''.join(random.choice(characters) for i in range(8))
        ExpFarmer.objects.filter(id=id).update(password=password)
        
        message = '''Welcome to OurWorkGem site.
        you can change automatically generated password after login to your profile
        Steps you should follow for changing password:
        1) Login your profile with autogenerated password
        2) After click on the profile button in the home page
        3) In that profile click on the change password button then you change the password
        You can login with this password : ''' +format(password)
        send_mail(subject, 
            message, EMAIL_HOST_USER, [recepient], fail_silently = False)
   return render(request,'site_admin/send_mail.html',{'exp':exp})

def send_remail(request,id):
   exp=ExpFarmer.objects.get(id=id)
   #sub = forms.Subscribe()
   if request.method == 'POST':
        sub = request.POST['email']
        name= request.POST['name']
        subject = 'Hi, '+format(name) 
        recepient = str(sub)
        message = '''Your registeration request is rejected... '''
        send_mail(subject, 
            message, EMAIL_HOST_USER, [recepient], fail_silently = False)
   return render(request,'site_admin/send_mail.html',{'exp':exp})