# Generated by Django 4.2 on 2023-04-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exfarmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expfarmer',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
