# Generated by Django 4.2 on 2023-05-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exfarmer', '0002_alter_expfarmer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='expfarmer',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expfarmer',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
